# syntax=docker/dockerfile:1
FROM golang:1.19-alpine AS builder
WORKDIR /app
COPY ./tcp_server/tcp_server.go .
RUN go build -o /bin/server ./tcp_server.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /bin/server /bin/server
EXPOSE 3333
CMD ["/bin/server"]